name       : kdeconnect
version    : 1.3.2
release    : 14
source     :
    - https://download.kde.org/stable/kdeconnect/1.3.2/src/kdeconnect-kde-1.3.2.tar.xz : 85878e483280f86ef86aa3f6f3a3369abc2ecb6c9ce1875d0f0ad685ec99e421
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - libfakekey-devel
rundeps    :
    - sshfs-fuse
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    %qml_cache
check      : |
    %make test || :
