name       : kdeconnect
version    : 21.08.2
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kdeconnect-kde-21.08.2.tar.xz : dbfd0eeef729be25b72f238a750d991db5e1fdeab386a0dea55172f00a1dbb25
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - kwayland-devel
    - kwayland-server-devel
    - libfakekey-devel
    - pulseaudio-qt-devel
    - qqc2-desktop-style-devel
rundeps    :
    - sshfs-fuse
    - kpeoplevcard
setup      : |
    %patch -p1 < $pkgfiles/openssh-8.2-fix.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
