name       : kdeconnect
version    : 20.08.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kdeconnect-kde-20.08.1.tar.xz : 8ebfe36b4d08b36881082a3748f63a7c645b51e8f3b094607512817e9f6ce668
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - kwayland-devel
    - kwindowsystem-devel
    - libfakekey-devel
    - pulseaudio-qt-devel
rundeps    :
    - sshfs-fuse
    - kpeoplevcard
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
