name       : kdeconnect
version    : 20.04.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kdeconnect-kde-20.04.0.tar.xz : 6ca93ee5e6bbc93b04e58a4327a5c7d434f112fd5fc8c47624e4974ffa09501f
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - kwayland-devel
    - kwindowsystem-devel
    - libfakekey-devel
    - pulseaudio-qt-devel
rundeps    :
    - sshfs-fuse
    - kpeoplevcard
setup      : |
    %patch -p1 < $pkgfiles/openssh-8.2-fix.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
