name       : kdeconnect
version    : 1.2.1
release    : 9
source     :
    - https://download.kde.org/stable/kdeconnect/1.2.1/src/kdeconnect-kde-v1.2.1.tar.xz : ef23eb8de8676f426298b244db426ad22e5212f26b3b435fd29a539fae186407
license    : GPL-2.0
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - libfakekey-devel
rundeps    :
    - sshfs-fuse
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
