name       : kdeconnect
version    : 23.04.2
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kdeconnect-kde-23.04.2.tar.xz : 2edbbe3e0aef7e6e19603a7870fd14ac0388a53ea665720c9ece625efb445a00
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(fuse)
    - pkgconfig(qca2-qt5)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpackage-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - kwayland-devel
    - libfakekey-devel
    - modemmanager-qt-devel
    - plasma-wayland-protocols-devel
    - pulseaudio-qt-devel
    - qqc2-desktop-style-devel
rundeps    :
    - sshfs-fuse
    - kpeoplevcard
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
