name       : kdeconnect
version    : '1.4'
release    : 20
source     :
    - https://cdn.download.kde.org/stable/kdeconnect/1.4/kdeconnect-kde-1.4.tar.xz : caee7945a9d9bb881a943dc8d2fd0d702c04da5bdb2df14d4f875e7cf5d5261a
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - kwayland-devel
    - libfakekey-devel
    - pulseaudio-qt-devel
rundeps    :
    - sshfs-fuse
    - kpeoplevcard
setup      : |
    %patch -p1 < $pkgfiles/openssh-8.2-fix.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache