name       : kdeconnect
version    : 22.04.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kdeconnect-kde-22.04.3.tar.xz : 9df40473469e73fbb865e1d0fcbe530b10b49d0f652f9265dd4237cae8ebaf04
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpackage-devel
    - kpeople-devel
    - kpeoplevcard-devel
    - kwayland-devel
    - libfakekey-devel
    - pulseaudio-qt-devel
    - qqc2-desktop-style-devel
rundeps    :
    - sshfs-fuse
    - kpeoplevcard
setup      : |
    %patch -p1 < $pkgfiles/openssh-8.2-fix.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove doc
    rm -rf $installdir/usr/share/doc
