name       : kdeconnect
version    : 1.2.0
release    : 6
source     :
    - https://download.kde.org/stable/kdeconnect/1.2/src/kdeconnect-kde-1.2.tar.xz : 5e8528a6758c64e884a787d661fc3ea38970e62e4540463238ad9a6c1b6d7970
license    : GPL-2.0
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - libfakekey-devel
rundeps    :
    - kirigami2
    - sshfs-fuse
setup      : |
    %cmake -DEXPERIMENTALAPP_ENABLED=ON .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
