name       : kdeconnect
version    : 1.3.4
release    : 17
source     :
    - https://origin.download.kde.org/stable/kdeconnect/1.3.4/kdeconnect-kde-1.3.4.tar.xz : 501057b752c3ec9791ca83f8fe592d8fd706d880fdfaf75a40d3546ed0dd328a
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDE Connect adds communication between KDE and your smartphone.
description: |
    KDE Connect is a multi-platform app that allows your devices to communicate (eg: your phone and your computer).
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - libfakekey-devel
rundeps    :
    - sshfs-fuse
setup      : |
    %cmake_ninja .
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
check      : |
    %make test || :
